# Zomato Exercise

Zomato is a restaurant aggregator website. The platform provides information, menus and user-reviews of restaurants as well as food delivery options from partner restaurants in select cities. You have been provided 3 datasets:

- zomato.csv contains restaurant information like average_cost_for_two, cuisines
- location.csv contains location of the restaurants like address, city, locality & etc
- ratings.csv contains aggregate rating for each restaurant

The different files are connected using the `id` columns which can be found in the different files. The id column is a unique identifier to represent a restaurant. You can use this to **merge** the different files.

In [1]:
import pandas as pd
import numpy as np

1. Merge the zomato, location & ratings file into a signle dataframe and store it to the `merged_df` variable **(3pts)**

In [2]:

zomato_df = pd.read_csv('/zomato.csv')
location_df = pd.read_csv('/location.csv')
ratings_df = pd.read_csv('/ratings.csv')

# Merge the datasets using the common column 'id'
merged_df = pd.merge(zomato_df, location_df, on='id')
merged_df = pd.merge(merged_df, ratings_df, on='id')

# Display the dimensions of table
print(merged_df.shape)

(6830, 35)

In [3]:
assert (6830, 35)==merged_df.shape

cols = ['id', 'address', 'city', 'city_id', 'country_id', 'latitude',
       'locality', 'locality_verbose', 'longitude', 'zipcode',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view',
       'is_delivering_now', 'is_table_reservation_supported',
       'is_zomato_book_res', 'menu_url', 'mezzo_provider', 'name',
       'photos_url', 'price_range', 'thumb', 'url']

assert sorted(merged_df.columns) == sorted(cols)

merged_df.head()

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,country_id,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes
0,6316125,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,...,162,14.560313,Salcedo Village,"Salcedo Village, Makati City",121.024638,NaN,4.9,3F7E00,Excellent,1394
1,18409457,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,...,162,14.552137,"Greenbelt 3, San Lorenzo, Makati City","Greenbelt 3, San Lorenzo, Makati City, Makati ...",121.021325,NaN,4.6,3F7E00,Excellent,602
2,6307689,1600,NaN,"American, Filipino",P,zomato://restaurant/6307689,https://www.zomato.com/manila/filling-station-...,https://b.zmtcdn.com/data/pictures/9/6307689/b...,0,0,...,162,14.563144,Poblacion,"Poblacion, Makati City",121.029800,1210.0,4.0,5BA829,Very Good,563
3,18581637,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,...,162,14.633713,Tomas Morato,"Tomas Morato, Quezon City",121.035026,NaN,4.0,5BA829,Very Good,413
4,6315438,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,...,162,14.546236,"SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.054365,NaN,4.6,3F7E00,Excellent,960

2. Create a function that returns the average aggregate rating for each city. Expected returned value is a Series datatype which contains name of city as index and average aggregate rating as value. **(2pts)**

In [4]:
def exercise_2(merged_df):
  return merged_df.groupby('city')['aggregate_rating'].mean()

In [5]:
res_series = exercise_2(merged_df)
assert True == np.isclose(3.302075, res_series[res_series.index == 'Pasay City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.890741, res_series[res_series.index == 'Valenzuela City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.558333, res_series[res_series.index == 'Malabon City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]

res_series

city
Caloocan City       1.953509
Las Piñas City      2.855738
Makati City         3.250512
Malabon City        1.558333
Mandaluyong City    2.951919
Manila              2.842652
Marikina City       2.672512
Muntinlupa City     2.962682
Parañaque City      3.130100
Pasay City          3.302075
Pasig City          2.916086
Pateros City        1.740000
Quezon City         2.887946
San Juan City       3.098462
Tagaytay City       2.959259
Taguig City         3.234105
Valenzuela City     1.890741
Name: aggregate_rating, dtype: float64

3. Using the apply function of pandas convert the rating_text to a numeric equivalent. You are to introduce a new column in merged_df called `rating_numeric` which is based on the value from rating_text: **(3pts)**

Excellent = 5 <br>
Very Good = 4 <br>
Good = 3 <br>
Average = 2 <br>
Poor = 1 <br>
Not rated = 0 <br>

In [6]:
def convert_rating(rating):
  if rating == 'Excellent':
    return 5
  elif rating == 'Very Good':
    return 4
  elif rating == 'Good':
    return 3
  elif rating == 'Average':
    return 2
  elif rating == 'Poor':
    return 1
  else:
    return 0

merged_df['rating_numeric'] = merged_df['rating_text'].apply(convert_rating)

print(merged_df[['name','rating_text', 'rating_numeric']].head())

                 name rating_text  rating_numeric
0   Mendokoro Ramenba   Excellent               5
1  Soban K-Town Grill   Excellent               5
2     Filling Station   Very Good               4
3      Romantic Baboy   Very Good               4
4      NIU by Vikings   Excellent               5

In [7]:
assert 868 == merged_df[merged_df.rating_numeric == 0].shape[0]
assert True == ('rating_numeric' in merged_df.columns)

4. Create a function which filters the merged dataframe to only contain rows coming in from a specific city. Expected returned value is a dataframe **(2pts)**

In [8]:
def exercise_4(merged_df, city):
    return merged_df[merged_df['city'] == city]

In [9]:

assert 'Makati City' == exercise_4(merged_df, 'Makati City').city.unique()[0]
assert (976, 36) == exercise_4(merged_df, 'Makati City').shape
exercise_4(merged_df, 'Mandaluyong City').head()

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes,rating_numeric
11,6318506,1500,NaN,"Japanese, Sushi",P,zomato://restaurant/6318506,https://www.zomato.com/manila/ooma-ortigas-man...,https://b.zmtcdn.com/data/res_imagery/6318506_...,0,0,...,14.583873,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056168,NaN,4.8,3F7E00,Excellent,762,5
13,6314302,1776,NaN,"Japanese, Korean",P,zomato://restaurant/6314302,https://www.zomato.com/manila/sambo-kojin-orti...,https://b.zmtcdn.com/data/pictures/chains/1/63...,0,0,...,14.584386,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056983,NaN,4.7,3F7E00,Excellent,570,5
15,18189371,1000,NaN,Chinese,P,zomato://restaurant/18189371,https://www.zomato.com/manila/din-tai-fung-ort...,https://b.zmtcdn.com/data/res_imagery/18189371...,0,0,...,14.583723,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056161,NaN,4.6,3F7E00,Excellent,657,5
18,6314111,1200,NaN,"Japanese, Ramen",P,zomato://restaurant/6314111,https://www.zomato.com/manila/ippudo-ortigas-m...,https://b.zmtcdn.com/data/pictures/chains/1/63...,0,0,...,14.583244,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.055956,NaN,4.6,3F7E00,Excellent,939,5
43,6315846,800,NaN,American,P,zomato://restaurant/6315846,https://www.zomato.com/manila/frankie-s-new-yo...,https://b.zmtcdn.com/data/res_imagery/6315846_...,0,0,...,14.583243,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.055954,NaN,4.4,5BA829,Very Good,575,4

In [10]:
assert 'Mandaluyong City' == exercise_4(merged_df, 'Mandaluyong City').city.unique()[0]
assert (443, 36) == exercise_4(merged_df, 'Mandaluyong City').shape
exercise_4(merged_df, "Mandaluyong City").head()

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes,rating_numeric
11,6318506,1500,NaN,"Japanese, Sushi",P,zomato://restaurant/6318506,https://www.zomato.com/manila/ooma-ortigas-man...,https://b.zmtcdn.com/data/res_imagery/6318506_...,0,0,...,14.583873,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056168,NaN,4.8,3F7E00,Excellent,762,5
13,6314302,1776,NaN,"Japanese, Korean",P,zomato://restaurant/6314302,https://www.zomato.com/manila/sambo-kojin-orti...,https://b.zmtcdn.com/data/pictures/chains/1/63...,0,0,...,14.584386,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056983,NaN,4.7,3F7E00,Excellent,570,5
15,18189371,1000,NaN,Chinese,P,zomato://restaurant/18189371,https://www.zomato.com/manila/din-tai-fung-ort...,https://b.zmtcdn.com/data/res_imagery/18189371...,0,0,...,14.583723,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056161,NaN,4.6,3F7E00,Excellent,657,5
18,6314111,1200,NaN,"Japanese, Ramen",P,zomato://restaurant/6314111,https://www.zomato.com/manila/ippudo-ortigas-m...,https://b.zmtcdn.com/data/pictures/chains/1/63...,0,0,...,14.583244,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.055956,NaN,4.6,3F7E00,Excellent,939,5
43,6315846,800,NaN,American,P,zomato://restaurant/6315846,https://www.zomato.com/manila/frankie-s-new-yo...,https://b.zmtcdn.com/data/res_imagery/6315846_...,0,0,...,14.583243,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.055954,NaN,4.4,5BA829,Very Good,575,4

In [11]:
assert (0, 36) == exercise_4(merged_df, 'Quezon  City').shape

exercise_4(merged_df, "Mandaluyong City").head()

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes,rating_numeric
11,6318506,1500,NaN,"Japanese, Sushi",P,zomato://restaurant/6318506,https://www.zomato.com/manila/ooma-ortigas-man...,https://b.zmtcdn.com/data/res_imagery/6318506_...,0,0,...,14.583873,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056168,NaN,4.8,3F7E00,Excellent,762,5
13,6314302,1776,NaN,"Japanese, Korean",P,zomato://restaurant/6314302,https://www.zomato.com/manila/sambo-kojin-orti...,https://b.zmtcdn.com/data/pictures/chains/1/63...,0,0,...,14.584386,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056983,NaN,4.7,3F7E00,Excellent,570,5
15,18189371,1000,NaN,Chinese,P,zomato://restaurant/18189371,https://www.zomato.com/manila/din-tai-fung-ort...,https://b.zmtcdn.com/data/res_imagery/18189371...,0,0,...,14.583723,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056161,NaN,4.6,3F7E00,Excellent,657,5
18,6314111,1200,NaN,"Japanese, Ramen",P,zomato://restaurant/6314111,https://www.zomato.com/manila/ippudo-ortigas-m...,https://b.zmtcdn.com/data/pictures/chains/1/63...,0,0,...,14.583244,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.055956,NaN,4.6,3F7E00,Excellent,939,5
43,6315846,800,NaN,American,P,zomato://restaurant/6315846,https://www.zomato.com/manila/frankie-s-new-yo...,https://b.zmtcdn.com/data/res_imagery/6315846_...,0,0,...,14.583243,"SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.055954,NaN,4.4,5BA829,Very Good,575,4

5. Create a function to filter the dataframe to only contain certain columns passed in the function. Expected returned value is a dataframe **(1pt)**

In [12]:
def exercise_5(merged_df, cols_to_filter):
    return merged_df[cols_to_filter]

In [13]:
cols = ['name', 'cuisines', 'city', 'aggregate_rating']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 4) == exercise_5(merged_df, cols).shape
exercise_5(merged_df, cols).head()

,name,cuisines,city,aggregate_rating
0,Mendokoro Ramenba,"Japanese, Ramen",Makati City,4.9
1,Soban K-Town Grill,"Korean, Grill, Korean BBQ",Makati City,4.6
2,Filling Station,"American, Filipino",Makati City,4.0
3,Romantic Baboy,Korean,Quezon City,4.0
4,NIU by Vikings,"Seafood, American, Mediterranean, Japanese",Taguig City,4.6

In [14]:
cols = ['average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 11) == exercise_5(merged_df, cols).shape

exercise_5(merged_df, cols).head()

,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,include_bogo_offers,is_book_form_web_view
0,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,True,0.0
1,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,True,0.0
2,1600,NaN,"American, Filipino",P,zomato://restaurant/6307689,https://www.zomato.com/manila/filling-station-...,https://b.zmtcdn.com/data/pictures/9/6307689/b...,0,0,True,0.0
3,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,True,0.0
4,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,True,0.0

6.  What is the most common restaurant name in the dataset? **(2pts)** Write down your answer and show code used to come up with the answer.

In [15]:
most_common_restaurant = merged_df['name'].mode()[0]
print('The most common restaurant name in the dataset is', most_common_restaurant)

The most common restaurant name in the dataset is Starbucks

7. Which restaurant has the most expensive average cost for two? **(2pts)** Write down your answer and show code used to come up with the answer.

In [16]:
most_expensive = merged_df['average_cost_for_two'].idxmax()
print('The restaurant with the most expensive average cost for two is', merged_df.loc[most_expensive, 'name'])

The restaurant with the most expensive average cost for two is The Tasting Room

8. How many restaurants do not have a zipcode? **(1pt)** Write down your answer and show code used to come up with the answer.

In [24]:
restaurants_without_zipcode = merged_df[['name','zipcode']].drop_duplicates('name').isnull().sum()
print('There are',restaurants_without_zipcode, 'restaurants without a zipcode.')

There are name          0
zipcode    3178
dtype: int64 restaurants without a zipcode.

9. How many restaurants in the dataset allow online delivery? **(1pt)** Write down your answer and show code used to come up with the answer.

In [33]:
restaurants_with_online_delivery = merged_df[['name','has_online_delivery']].drop_duplicates('name')['has_online_delivery'].sum()
print('There are', restaurants_with_online_delivery, 'restaurants that allow online delivery.')

There are 0 restaurants that allow online delivery.

10. Which locatlity has more expensive food? Poblacion or Salcedo Village? **(3pts)** Write down your answer and show code used to come up with the answer.

In [34]:
poblacion_avg_cost = merged_df[merged_df['locality'] == 'Poblacion']['average_cost_for_two'].mean()
salcedo_avg_cost = merged_df[merged_df['locality'] == 'Salcedo Village']['average_cost_for_two'].mean()

print()
if poblacion_avg_cost > salcedo_avg_cost:
  print('Poblacion has more expensive food.')
else:
  print('Salcedo Village has more expensive food.')

Salcedo Village has more expensive food.